AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 40
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/BlockLength:
  Max: 40

Metrics/ClassLength:
  Max: 200
