#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)

Encoding::default_internal = Encoding::UTF_8
Encoding::default_external = Encoding::UTF_8

require 'vps'

begin
  VPS::Cli.new.run
rescue Exception => e
  if e.message != 'exit' # There's probably a better way to do this...
    puts e.message
    exit(-1)
  end
end
